# Generated by Django 6.0.4 on 2026-04-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.BooleanField(choices=[(True, 'Taip'), (False, 'Ne')], default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.BooleanField(choices=[(True, 'Taip'), (False, 'Ne')], default=True),
        ),
    ]
